# Generated by Django 6.1.1 on 2026-09-24 04:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('nombre_corto', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1x2', 'Resultado (1 X 2)'), ('ou25', 'Goles 2.5'), ('dc', 'Doble oportunidad'), ('dnb', 'Empate no válido'), ('btts', 'Ambos marcan'), ('ht1x2', 'Resultado al descanso'), ('ou15', 'Goles 1.5'), ('ou35', 'Goles 3.5'), ('cor95', 'Córners 9.5'), ('tar45', 'Tarjetas 4.5')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('anio', models.PositiveSmallIntegerField(unique=True)),
                ('activa', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('etiqueta', models.CharField(max_length=80)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='cuota vigente')),
                ('cuota_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('resultado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ganada', 'Ganada'), ('perdida', 'Perdida'), ('nula', 'Nula (se devuelve)')], default='pendiente', max_length=10)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='apuestas.mercado')),
            ],
            options={
                'verbose_name': 'opción',
                'verbose_name_plural': 'opciones',
                'ordering': ['mercado', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='cuota fijada')),
                ('cuotas_mercado', models.JSONField()),
                ('suma_inversas', models.DecimalField(decimal_places=5, max_digits=8)),
                ('creada', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas', to=settings.AUTH_USER_MODEL)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuestas', to='apuestas.opcion')),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_numero', models.PositiveSmallIntegerField(verbose_name='fecha')),
                ('inicio', models.DateTimeField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_juego', 'En juego'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido')], default='programado', max_length=12)),
                ('goles_local', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goles_visita', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goles_local_ht', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='goles local al descanso')),
                ('goles_visita_ht', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='goles visita al descanso')),
                ('corners', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='córners totales')),
                ('tarjetas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='tarjetas totales')),
                ('cuotas_cierre_fijadas', models.BooleanField(default=False)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_local', to='apuestas.equipo')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_visita', to='apuestas.equipo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='apuestas.temporada')),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
        migrations.AddField(
            model_name='mercado',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercados', to='apuestas.partido'),
        ),
        migrations.AddConstraint(
            model_name='opcion',
            constraint=models.UniqueConstraint(fields=('mercado', 'codigo'), name='opcion_unica_en_mercado'),
        ),
        migrations.AddConstraint(
            model_name='apuesta',
            constraint=models.CheckConstraint(condition=models.Q(('unidades__gte', 1), ('unidades__lte', 10)), name='unidades_entre_1_y_10'),
        ),
        migrations.AddConstraint(
            model_name='mercado',
            constraint=models.UniqueConstraint(fields=('partido', 'tipo'), name='un_mercado_por_tipo'),
        ),
    ]
