# Generated by Django 6.1.1 on 2026-09-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0002_usuario_foto_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='correo confirmado'),
        ),
    ]
