"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ------------------------------------------------------------------
# Seguridad. En tu computador se usan los valores por defecto (modo
# desarrollo). En internet, PythonAnywhere define estas variables de
# entorno y la página corre en modo seguro.
# ------------------------------------------------------------------
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise RuntimeError('Falta la variable DJANGO_SECRET_KEY en el servidor.')
    SECRET_KEY = 'solo-para-desarrollo-local-no-usar-en-internet'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS if h not in ('localhost', '127.0.0.1')]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # En internet, cada versión de estilos.css / *.js recibe un nombre distinto
    # (p. ej. estilos.3f9a1c.css). Así los navegadores no usan copias viejas.
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'},
    }


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apuestas',
]

MIDDLEWARE = [
    'apuestas.respaldo_automatico.RespaldoDiarioMiddleware',   # respaldo diario (solo en internet)
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apuestas.contexto.sitio',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# Carpeta donde `collectstatic` junta CSS y JS para servirlos en internet
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Archivos que suben los usuarios (fotos de perfil)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Respaldos de la base de datos (ver apuestas/respaldo_automatico.py).
# En internet se crean solos una vez al día; en tu computador, no.
RESPALDOS_DIR = Path.home() / 'respaldos'
RESPALDO_AUTOMATICO = not DEBUG


# Correo. En internet se envía con Gmail (el único permitido en el plan
# gratis de PythonAnywhere); el usuario y la "contraseña de aplicación" se
# definen en el archivo WSGI del servidor. En tu computador, los correos no
# se envían: se muestran en la ventana donde corre el servidor.
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
EMAIL_USUARIO = os.environ.get('EMAIL_USUARIO', '')
if EMAIL_USUARIO:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'OPTIONS': {
                'host': 'smtp.gmail.com',
                'port': 587,
                'username': EMAIL_USUARIO,
                'password': os.environ.get('EMAIL_CLAVE', ''),
                'use_tls': True,
                'timeout': 20,
            },
        },
    }
else:
    MAILERS = {'default': {'BACKEND': 'django.core.mail.backends.console.EmailBackend'}}

# Cuánto duran los enlaces de activación y de nueva contraseña (3 días)
PASSWORD_RESET_TIMEOUT = 3 * 24 * 60 * 60

# Usamos nuestro propio modelo de usuario (apuestas.Usuario) para poder
# agregarle campos más adelante sin dolor.
AUTH_USER_MODEL = 'apuestas.Usuario'

# Nombre provisorio de la página: cámbialo aquí y se actualiza en todas partes.
NOMBRE_SITIO = 'Pronostika'
DEFAULT_FROM_EMAIL = f'{NOMBRE_SITIO} <{EMAIL_USUARIO or "no-responder@localhost"}>'

# Muestra la etiqueta amarilla "Datos de ejemplo" en la barra superior.
# Ponlo en False cuando conectemos la API de cuotas reales.
DATOS_DE_EJEMPLO = True

# Adónde mandar a alguien que intenta apostar sin haber iniciado sesión, y adónde
# volver después de entrar o salir.
LOGIN_URL = 'entrar'
LOGIN_REDIRECT_URL = 'partidos'
LOGOUT_REDIRECT_URL = 'ranking'
